version: '3'
services:
  frontend:
    build: ./frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./feedback-service
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:pass@db:5432/feedback_db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: feedback_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
